version: "3"
services:

  mysql:
    image: mysql:8.0
    container_name: mysql
    command: mysqld --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql-data:/var/local/mysql/data
    ports:
      - "3306:3306"
    hostname: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=mysql

  maven-app:
    build: sample-maven-app
    image: sample-maven-app
    container_name: sample-maven-app
    hostname: maven-app
    tty: true
    depends_on:
      - mysql

volumes:
  mysql-data:
    driver: local